networks:
  web:
    external: true

services:
  web:
    image: lorispcin/awaa:latest
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    container_name: meteo
    restart: unless-stopped
    labels:
      - traefik.http.routers.awaa.rule=Host(`meteo.lorisperc.in`)
      - traefik.http.routers.awaa.tls=true
      - traefik.http.routers.awaa.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - web