networks:
  web:
    external: true

services:
  web:
    image: lorispcin/awaa:latest
    build:
      context: .
    environment:
      NODE_ENV: production
    container_name: awaa
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.awaa.rule=Host(`meteo.lorisperc.in`)
      - traefik.http.routers.awaa.service=web-awaa
      - traefik.http.routers.awaa.entrypoints=web
      - traefik.http.routers.awaa.entrypoints=websecure
      - traefik.http.routers.awaa.tls=true
      - traefik.http.routers.awaa.tls.certResolver=default
      - traefik.http.services.awaa.loadbalancer.server.port=8080
    networks:
      - web